paths:
  /api/products/:
    get:
      summary: Obtiene los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos correctamente de la base de datos
        "500":
          description: Error interno del servidor usualmente generado por una query defectuosa o un fallo en la base de datos
  